name: Build/release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    permissions:
      contents: write

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - run: sudo apt install -y libarchive-tools
      - run: sudo snap install snapcraft --classic
      - run: sudo snap install multipass --beta --classic

      - run: npm ci
      # dist
      - run: npm run release
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}

      - env:
          BUILDKITE_TOKEN: ${{ secrets.BUILDKITE_TOKEN }}
        run: |
          for f in ./dist/*.deb; do
            curl -s -X POST https://api.buildkite.com/v2/packages/organizations/piec/registries/elecwhat-deb/packages \
              -H "Authorization: Bearer $BUILDKITE_TOKEN" \
              -F "file=@$f"
          done

          for f in ./dist/*.rpm; do
            curl -s -X POST https://api.buildkite.com/v2/packages/organizations/piec/registries/elecwhat-rpm/packages \
              -H "Authorization: Bearer $BUILDKITE_TOKEN" \
              -F "file=@$f"
          done
